### ISSUE TITLE
Generate edit/create form

### ISSUE THREAD

**Issue by kamov** [Okipa/laravel-bootstrap-table-list#10]
First of all congrats and big thanks for this library, it's saved me a lot of time, very nice and useful.

I would like to suggest an idea to make create/edit form generation, would be great.

Do you already think about? Or there is another solution for do that?

So basically adding routes for create and edit, can be possible to setup to show the form.

Best

**Comment by Okipa** [comment]
Hi @kamov, very sorry for the late reply and thanks for your message !
The purpose of this package is not to generate forms but to generate table lists directly from PHP and not from javascript. But if you intend to automatically generate your forms, I think there are other packages to do that.
If you use bootstrap 4, you can take a look to https://github.com/Okipa/laravel-bootstrap-components, which allows you to save time for your form building, this is what I use.
I do not automatically generate my forms but I'm sure you can find some good Laravel package to perform this out here ! 

Edit : The route you fill in the tablelist are used when you hit the create / edit / delete buttons. The package let you then build the treatments to perform those actions.
