### ISSUE TITLE
Search input group : Wrong button sizes

### ISSUE THREAD

**Issue by jamesst20** [Okipa/laravel-bootstrap-table-list#11]
<img width="1161" alt="screen shot 2019-02-10 at 9 23 21 am" src="https://user-images.githubusercontent.com/490234/52534923-d7d2f280-2d15-11e9-8d62-8497cf4f773f.png">

Packages.json content :

```
  "devDependencies": {
        "bootstrap": "^4.0.0",
        "cross-env": "^5.1",
        "jquery": "^3.2",
        "laravel-mix": "^4.0.7",
        "popper.js": "^1.12",
        "resolve-url-loader": "^2.3.1",
        "sass": "^1.15.2",
        "sass-loader": "^7.1.0",
        "@fortawesome/fontawesome-free": "^5.7.1"
    }
```

**Comment by Okipa** [comment]
Hi @jamesst20, thanks for your request.  
This package is abandoned and has been moved here : https://github.com/Okipa/laravel-table
However, if you still want to use this one, I would accept PR to fix this.

**Comment by jamesst20** [comment]
Thank you @Okipa

I should be able to upgrade to the new version then :) I wasn't aware of that
