### ISSUE TITLE
Add custom HTML class to <td>s

### ISSUE THREAD

**Issue by stephandesouza** [Okipa/laravel-bootstrap-table-list#5]
Add a method to TableListColumn which can add a custom class to every <td> element.

**Comment by Okipa** [comment]
It would indeed be possible to add some optional methods that would allow to make some design customizations.
As I see it, it would be something like that :

**TableList**
```
$table = app(TableList::class)
    ->setTableModel(News::class)
    ->setRoutes([
        'index' => ['alias' => 'news.index', 'parameters' => []],
    ])
    ->addClassesToTableHtmlElement(['custom-table-class', 'another-custom-table-class'])
    ->addClassesToTrHtmlElements(['custom-tr-class', 'another-custom-tr-class'])
    ->addClassesToTdHtmlElements(['custom-td-class', 'another-custom-td-class'])
```

The method name are quite long but as this package will evolve, it is important to keep it intuitive and easily understandable.

**Comment by Okipa** [comment]
The V2 package configuration does now let you set the custom class for almost all elements of the table list.
As so, the creation of new methods to give custom styles to only one table does not make sense to me.
I close this issue, let me know if the new version brings you the customization possibilities you want.
