### ISSUE TITLE
error in setModel method

### ISSUE THREAD

**Issue by janisbarons** [Okipa/laravel-bootstrap-table-list#7]
Hello. I have some problem.
when I try:
` ->setModel(Project::class)`
I get:
`Argument 1 passed to Okipa\LaravelBootstrapTableList\TableList::setModel() must be an instance of Okipa\LaravelBootstrapTableList\string, string given`

**Comment by Okipa** [comment]
Hi @janisbarons, I will try to look into this this afternoon.
I come back to you as soon as I have more informations about this.

**Comment by janisbarons** [comment]
@Okipa everything is okey right now. it turned out, that my apache was loading incorrect php version on server after recent php version upgrade.. Thanks for your great package!

**Comment by Okipa** [comment]
@janisbarons nice. I close the issue as this wasn't a package problem.
